# Generated by Django 6.0.3 on 2026-03-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chargeback',
            fields=[
                ('id_chargeback', models.AutoField(primary_key=True, serialize=False)),
                ('empresa_pagadora', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_motivo', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo_informado', models.CharField(blank=True, max_length=255, null=True)),
                ('id_transacao_pagarme', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_aluno', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_aluno', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_processo', models.CharField(default='Pendente', max_length=50)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chargeback',
                'managed': False,
            },
        ),
    ]
